apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-config
  labels:
    app: catalog-service
data:
  application.yml: |
    bookshop:
      greeting: Welcome to the book catalog from Kubernetes!
      testdata:
        enabled: true
    spring:
      datasource:
        url: jdbc:postgresql://bookshop-postgres/bookshop_catalog