apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  labels:
    app: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8000"
    spec:
      containers:
        - name: catalog-service
          image: ghcr.io/rajanjha786/catalog-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                # Send the SIGTERM signal to pod after 5 seconds after informing all the components to not send the request to this pod
                command: ["sh", "-c", "sleep 5"]
          ports:
            - containerPort: 8000
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://catalog-postgres/bookshop_catalog
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service
            - name: POLAR_TESTDATA_ENABLED
              value: "true"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 15