apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  labels:
    app: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: ghcr.io/rajanjha786/catalog-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                # Send the SIGTERM signal to pod after 5 seconds of informing all the components to not send the request to this pod
                command: ["sh", "-c", "sleep 5"]
          ports:
            - containerPort: 8000
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://catalog-postgres/bookshop_catalog